"""messaging: conversations and messages tables

WHAT THIS MIGRATION DOES, IN PLAIN ENGLISH.

Creates two brand-new tables and one index. It changes no existing table and
touches no existing row.

THAT IS WHY THERE IS NO BACKFILL HERE, and it is worth saying out loud after
migration 44f1de93ab3b, where leaving the backfill out would have locked six
real accounts out of posting.

The difference is not that this one is safer to write. It is that "what should
these columns say for rows that already exist" is a question with no subject:
there are no existing conversations, because conversations have never existed
before. Autogenerate could write the whole of this one precisely because there
was no judgement to make.

The two rules on `conversations` are the interesting part, and they only work
as a pair:

  uq_conversations_pair          this pair of people may only appear once
  ck_conversations_ordered_pair  the smaller user id must be in user_a_id

Without the second, (3, 7) and (7, 3) count as different pairs and the unique
rule allows both -- which is the exact bug it was added to prevent. See the
Conversation class in models.py for the full explanation.

Note the "<" rather than "<>": equal fails it, so a conversation with yourself
is impossible too.

Revision ID: 9a3a098972b6
Revises: 44f1de93ab3b
Create Date: 2026-09-01 22:47:22.771878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3a098972b6'
down_revision: Union[str, Sequence[str], None] = '44f1de93ab3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_a_id', sa.Integer(), nullable=False),
    sa.Column('user_b_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_a_id < user_b_id', name='ck_conversations_ordered_pair'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='uq_conversations_pair')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_id_id', 'messages', ['conversation_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop both, messages first.

    THE ORDER MATTERS AND AUTOGENERATE GOT IT RIGHT. messages.conversation_id
    points at conversations, so dropping conversations first would leave rows
    pointing at a table that no longer exists -- PostgreSQL refuses, and the
    downgrade fails half way.

    Genuinely lossless in the sense that matters: nothing that existed before
    this migration is touched. Everything it destroys is something it created.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_id_id', table_name='messages')
    op.drop_table('messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###
